name: Send Reserved Messages

on:
  schedule:
    - cron: '57 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name : Install Dependencies 
      run: npm install
    - name : Send Reserved Messages on Notion
      run : |
        MAX_RETRIES=10
        COUNT=0
        SUCCESS=0
        while [ $COUNT -lt $MAX_RETRIES ]; do
          npx tsc && node app.js && SUCCESS=1 && break
          COUNT=$((COUNT + 1))
          echo "Attempt $COUNT failed. Retrying in 2 seconds..."
          sleep 2
        done
        if [ $SUCCESS -eq 0 ]; then
          echo "All attempts failed."
          exit 1
        fi
      env : 
        NOTION_TOKEN : ${{secrets.NOTION_TOKEN}}
        LINK_DATABASE_URL : ${{secrets.LINK_DATABASE_URL}}
